/*
* generated by Xtext
*/
package de.hsos.richwps;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class WDUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return de.hsos.richwps.ui.internal.WDActivator.getInstance().getInjector("de.hsos.richwps.WD");
	}
	
}
