/*
 * generated by Xtext
 */
package de.hsos.richwps.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class WDUiModule extends de.hsos.richwps.ui.AbstractWDUiModule {
	public WDUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
