/*
 * generated by Xtext
 */
package de.hsos.richwps;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class WDRuntimeModule extends de.hsos.richwps.AbstractWDRuntimeModule {

}
