/*
 * generated by Xtext
 */
package de.hsos.richwps.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.hsos.richwps.ui.internal.WDActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class WDExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return WDActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return WDActivator.getInstance().getInjector(WDActivator.DE_HSOS_RICHWPS_WD);
	}
	
}
