/*
* generated by Xtext
*/
package de.hsos.richwps;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class WDStandaloneSetup extends WDStandaloneSetupGenerated{

	public static void doSetup() {
		new WDStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

